### PR TITLE
First pull request

### PR DESCRIPTION
**Pull request by 0203ANU**

### CODE REVIEW

**Comment by enkeboll** [comment]
Open this in your repository against the your `main` branch! See my comments on Slack ([link](https://umbcdatasci.slack.com/archives/C032AHG2V3J/p1644078222559719)) if you have questions

**Comment by 0203ANU** [comment]
Thanks for the quick response professor. I am trying again to make a pull
request from my main. However, while I m trying to add your user name in
reviewers, It just won't show anything.

Can you please bring some light to that?

**Comment by enkeboll** [comment]
Have you invited me to be a collaborator yet?

**Comment by 0203ANU** [comment]
Yes, professor. I have just made a pull request#1 from my main. Added you
as a collaborator. The request is still pending. I guess I have correctly
made a pull request?

**Comment by 0203ANU** [comment]
Hi professor can you please confirm if I have successfully made a pull
request? I have done everything so far according to the link you shared on
slack. Just to be sure.

Thanks

**Comment by enkeboll** [comment]
I don't see any pull requests on your repository
https://github.com/0203ANU/data603-sp22/pulls

**Pull request closed without merging**
